### ISSUE TITLE
Brak obrazka w sekcji bezalkoholowe napoje

### ISSUE THREAD

**Issue by vladdrakula02** [vladsesmii26/pizzeriaDaVinci#6]
Cześć, zauważyłem że w sekscji  z bezalkolowymi napojami nie ma obrazka, zdaje się że trzeba to poprawić.

**Comment by vladsesmii26** [comment]
commit cfc434a00c2c6cf20dd3ef6e5b1d6fa4327807af naprawia ten błąd

**Comment by vladsesmii26** [comment]
cfc434a00c2c6cf20dd3ef6e5b1d6fa4327807af fixes #6
